import type { MdxFile } from '../core/mdx-reader.js'

/**
 * Generates /llms.txt content from MDX frontmatter.
 * Format: one entry per line — URL, title, description.
 */
export function generateLlmsTxt(files: MdxFile[], baseUrl: string): string {
  const lines: string[] = [
    '# LLMs.txt — AI-readable content index',
    `# Generated by third-audience-mdx`,
    '',
  ]

  for (const file of files) {
    const fm = file.frontmatter
    const url = `${baseUrl.replace(/\/$/, '')}/${file.slug}`
    const title = String(fm.title ?? file.slug)
    const desc = fm.description ? ` — ${String(fm.description)}` : ''
    lines.push(`- [${title}](${url})${desc}`)
  }

  return lines.join('\n') + '\n'
}
